name: Deploy React App to GH Pages

on:
    push:
        branches: ['master']
permissions:
    contents: read
    pages: write      
    id-token: write
    
jobs:
  build-angular:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  

      - name: Install Dependencies
        run : npm install
        
      - name: Build React App
        run : npm run build

      - name: Archieve build artifacts
        uses : actions/upload-artifact@v4
        with : 
          name : 'react-build'
          path : build
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
            token: ${{secrets.GITHUB_TOKEN}}
            artifact_name: 'react-build'