name: Deploy React App to GH Pages

on:
    push:
        branches: ['master']
permissions:
    contents: read
    pages: write      
    id-token: write
    actions: read

jobs:
  build-react:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  

      - name: Install Dependencies
        run : npm install
        
      - name: Build React App
        run : npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3   
        with:
         name: 'github-pages'
         path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'